## Your program name, change it accordingly.
PROGNAME=CoolApp

## Enable Opt-In Features, when True, a extra setup page will be shown so the user can choose what to install and what to ignore.
HASOPTINFEATURES=True

## Required if the HASOPTINFEATURES flag is set to "True", if not, it is highly possible that the user will be hit with an empty page and annoyance at you.
OPTINDIR=OPTIN/

## This list's contents are specified in OPTIN/README.md
FEATURELISTFILE=OPTIN/features.conf

## If your application has a icon, drop it on the "Icons" directory, or point to it inside your binary files if you have them there.
ICON=Icons/SetupWizardIcon.png

# If this is set to true, the system will automatically have a copy of the README.txt file copied to the installation directory after the software is installed.
HASREADME=True
## Required if HASREADME is set to True.
READMEFILE=README.md

## The included LICENSE to display when on setup.
LICENSEFILE=TestLicense

## LDS Software Setup 0.0.23 and upwards, SKIPINTEGRITYCHECK is available for Software Upgrade Packages.
## Skips the integrity check and overwrittes all files from definstdir or selected installation directory if set to true, if set to false, it notifies the user that it cannot proceed with installation without confirming operation.
SKIPINTEGRITYCHECK=False
## This is the binary name of the Launcher that launches your application, if it is empty, your application will fail to launch when the user clicks "Open $NAME" after the installation is done.
## It is recommended this value ALWAYS points to the binary that launches your application.
MAINBINNAME=CoolApp

# Specify to the setup if we want to create a directory with the INSTDIRNAME name.
MKDIR=True

# Define the Software's installation directory, this NEEDS to exist if we set MKDIR to true.
INSTDIRNAME="ExampleApp"

## This, is Path on which the program defaults is installation(Relative to $HOME, as this Wizard expects to be installed as UserOnly mode.)
## we still ask for a path to install, but we default the FilePicker to this path instead of $HOME or "/".
DEFINSTDIR=System/Programs


 # Do not symlink installed files to $HOME/System/Programs or /usr/bin.
SYMLINKFILES=False ## This is a indev feature.

 # This can be either "User" for the $HOME path type, or "Global" to install in /usr/bin, Global will ask for a password before installing the software, to ensure we can write to /usr/bin.
DEFINSTTYPE=User

## Copyright Specific fields.
## If the software we are installing has a copyright, we add this below the program name with the corresponding copyright symbol and holder.
HASCOPYRIGHT=True

# The company that holds the copyright of the software users will install. It is recommended you fill this if your application falls under the Copyright Law for Reserved Names.
COPYHOLDER="YourCompanyName"

# Ask the user if they want to open the newly installed software after installation. this will appear after installation is complete, alongside the "Open Readme" if "HASREADME" is set to true.
ASKIFOPENONEND=True ## If this is not set or available, we default to true.