#ifndef SETUPWIZARD_HPP
#define SETUPWIZARD_HPP

// Start Of: Static strings and values
// Corporate told me to not hardcode these... i hardcoded them anyways. fight me >:3
// - Lilly Aizawa @ LDS Softworks LLC
#define InstallerVersion        "Version 0.0.23"

#define ProgramWindowName       "Setup Wizard"
// Weird markup issues forced me to hardcode this string.
#define ProgramAboutWindowName  "About Software Setup Wizard©"

// EULA Agreement message
#define AcceptLicenseAgreement  "I accept the terms in the End User License Agreement"

// Setup Configuration File
#define SetupConfigFile         "setup.conf"

// UI Buttons
#define UIButton_Back           "< Back"
#define UIButton_Next           "Next >"
#define UIButton_Install        "Install"
#define UIButton_Finalize       "Finish"
#define UIButton_Cancel         "Cancel"

// Embedded CSS for GTK to keep the Win-95 Style... -ish.
const char win95_css[] =
            "* { "
            "  font-family: 'MS Sans Serif', 'Tahoma', sans-serif; "
            "  font-size: 11px; "
            "  -GtkHTML-fixed-font-size: true; "
            "} "
            "window, .background { "
            "  background-color: #c0c0c0; "
            "  color: black; "
            "} "
            "button { "
            "  background-image: none; "
            "  background-color: #c0c0c0; "
            "  color: black; "
            "  border-radius: 0; "
            "  border: 2px solid; "
            "  border-color: #ffffff #808080 #808080 #ffffff; "
            "  padding: 2px 10px; "
            "  box-shadow: none; "
            "} "
            "button:active, button:checked { "
            "  border-color: #808080 #ffffff #ffffff #808080; "
            "  padding: 3px 9px 1px 11px; "
            "} "
            "button:hover { "
            "  background-color: #c0c0c0; "
            "} "
            "notebook { "
            "  background-color: #c0c0c0; "
            "  border: none; "
            "} "
            "entry, treeview, textview, scrolledwindow { "
            "  background-color: white; "
            "  color: black; "
            "  border-radius: 0; "
            "  border: 2px solid; "
            "  border-color: #808080 #ffffff #ffffff #808080; "
            "} "
            "separator { "
            "  min-height: 2px; "
            "  background-color: transparent; "
            "  border-top: 1px solid #808080; "
            "  border-bottom: 1px solid #ffffff; "
            "} "
            "checkbutton check { "
            "  border-radius: 0; "
            "  border: 2px solid; "
            "  border-color: #808080 #ffffff #ffffff #808080; "
            "  background-color: white; "
            "  box-shadow: none; "
            "  min-height: 12px; "
            "  min-width: 12px; "
            "} "
            "checkbutton check:checked { "
            "  background-image: url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iOCIgaGVpZ2h0PSI4IiB2aWV3Qm94PSIwIDAgOCA4IiBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxwYXRoIGQ9Ik0xIDRMMyA2TDcgMiIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSIyIi8+PC9zdmc+'); "
            "  background-repeat: no-repeat; "
            "  background-position: center; "
            "}";


// User Warning for Missing License, this is for security reasons, and to avoid users blaming ME for other Developers' bad usage of my software.
static char ENOLICENSEADVISORY[] = "\t\t\t\tWAIT!!\n\n"
          "The software you're trying to install does not provide a license, proceed with care, as this "
          "Setup Program does not check for malicious behavior.\n\nPlease "
          "review the program's verity before installing.\n"
          "\nIf you wish to continue, it is important to note, that this setup "
          "utility(As well as LDS Softworks LLC) does not make themselves "
          "responsible for any damage caused, monetary losses, or other kind of "
          "cyber-attack aftermath of installing unverified software on your PC may cause.\n\n"
          "As this Setup Utility is given under the MIT License and is provided AS IS without ANY WARRANTY of what it may be used for.\n"
          "\n---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n"
          "\n\tNote: Links included in this next section are NOT affiliated to "
          "LDS or LDS Softworks LLC in any way, they simply serve as a collection of "
          "'Related Content' or 'Helpful Links'\n"
          "\n---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n"
          "\n\tYou can know more about the MIT License Agreement in here: "
          "https://en.wikipedia.org/wiki/MIT_License\n\n"
          "\tYou can also learn about 'LICENSES' in here: \n"
          "\t(English Video by 'Sandip Das' on YouTube) "
          "https://www.youtube.com/watch?v=Jj75JOiV9uA\n"
          "\t(Video En Español por 'OpenWebinars' en YouTube) "
          "https://www.youtube.com/watch?v=Sz07vfAlqYo\n"
          "\n---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n"
          "\n\nPlease ensure you TRUST the publisher of the provided software "
          "before installing it."
          "\nYou must accept this Agreement to continue with the installation "
          "UNDER YOUR OWN RISK AND KNOWLEDGE."
          "\n\n\n\n\n"
          "If you are a developer seeing this, A license file is highly required when "
          "approaching installation of software, this file ensures users don't "
          "illegally copy, distribute, sell or tamper with your program's "
          "files without you permissions, as well, it helps THE USER knows "
          "their Software Rights.\nThis is not obligatory to be a GPL or MIT "
          "License Type, but can be any kind of license, as long as it is explicit and detailed on its clausules."
          "\n\nThe purpose of this, is to ensure that You(THE DEVELOPER) can trust on the END "
          "USER, by offering them an END-USER LICENSE AGREEMENT stating their "
          "rights and allowed actions against your software, as well as your "
          "responsibility as THE DEVELOPER, without one, it is highly possible "
          "WE(This Setup Utility), continues to mark your software as "
          "UNTRUSTWORTHY.\n\n"
          "Be a responsible developer, and please add the required LICENSE files, as this protects YOU and THE USER from any kind of miuse by third-parties.";

// End Of: Static strings and values
#endif